language: clojure

before_install:
  - "gem install bundler"
  - "cd clojure/engine"

env:
  - CLOJURE_DIR="../engine"
  - CLOJURE_DIR="../console"
  - CLOJURE_DIR="../web_app/joodo"
  - RUBY_DIR = "../../ruby/engine"

script:
  - "cd $CLOJURE_DIR && lein deps && lein spec"
  - "cd $RUBY_DIR && bundle install && rspec"
