source 'https://rubygems.org'

gem 'sinatra-contrib'
gem 'sinatra'
gem 'taka_tic_tac_toe', :git => "https://github.com/TakaGoto/taka_tic_tac_toe.git"

group :test do
  gem 'rake'
  gem 'rspec'
  gem 'rack-test'
  gem 'pry'
end

